spring.application.name=employee-manage-project
spring.datasource.url= jdbc:mysql://localhost:3306/employee_management_db
spring.datasource.username = root
spring.datasource.password =
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.base64-secret = dQk+azaZCGj1hH5EPcuFZfQ26xeQqFzoSAEzMg5jBPY=

telegram.bot.token = 8919365131:AAE1Uysa4EB6aUZGmPslCUAcCHjwyOcbIN8
telegram.bot.chat-id = -5395845432

spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.org.hibernate.SQL=DEBUG

server.port=8081